### PR TITLE
setFormValue: Adds support for FormData

### LINKED ISSUE #18: setFormValue should accept null values
Expected Behavior:
When defining a checkbox in a form,  checking the checkbox will set a form key value pair.  When the checkbox is deselected, the [key,value] pair is remove.

Current Behavior:
When deselecting a checkbox, the key is still available with a value of "undefined".

### LINKED ISSUE #20: Non-name form elements create a null FormData key
Current behavior:

1. Create a custom element with form associated.
2. Do not add a name attribute.
3. Serialize FormData
4. You will see a key of null

Expected behavior:
1. Create a custom element with form associated.
2. Do not add a name attribute.
3. Serialize FormData
4. You shouldn't see the element in the form

### PR DESCRIPTION
**Pull request by lideen**
This PR adds support for passing FormData to setFormValue to allow setting multiple form values as supported in the Chrome implementation. Not sure if you had something else in mind already considering https://github.com/calebdwilliams/element-internals-polyfill/issues/17 but I thought I'd share anyway if you're interested in merging this.

Edit: I think this also closes #18 

Edit 2: Closes #20

### CODE REVIEW

**Comment by calebdwilliams** [comment]
This is great, I absolutely want this but have been putting it off. I want to put this through it’s paces a bit first. 

One thing I want to check is behavior as those FormData keys are changed up a bit. I really like this though and after verifying behavior, I’ll add this.

**Comment by lideen** [comment]
After some more testing I found some bugs that I adressed (updated tests for these as well): 

1. Multi-valued keys did not work if set in the FormData, ex:
   ```js
   const formData = new FormData()
   formData.set("multivalue", "1");
   formData.append("multivalue", "2");
   ```
1. Fix for #20 but still allow to set form values via FormData if name is not set on the element

**Comment by lideen** [comment]
Also, I'm not sure if the FormData patch is needed anymore? I tried to remove it and all tests still pass and seems to work with my code, not sure if I'm missing something though? 🤔

**Review by calebdwilliams — APPROVED** [review]
I'm guessing the form data patch isn't needed any more now that we're using the hidden inputs. I'll look into that as I'm implementing validation anchor. This PR looks great, are you happy with where this is? If so, I'm ready to merge and release.

**Comment by lideen** [comment]
Yeah, go ahead 😃

**Comment by calebdwilliams** [comment]
These updates are in version 0.1.3. Thanks @lideen!

**Pull request merged**
