### PR TITLE
respect novalidate attribute

### PR DESCRIPTION
**Pull request by elmerbulthuis**
When novalidate is set on a form, we don't want to validate on submit. And don't want to stop the events from propagating.

### CODE REVIEW

**Review by calebdwilliams — CHANGES_REQUESTED** [review]
Left a comment, but I'm not sure if it was seen or not. Can we add a test for this behavior just so we don't lose it in regression? This is a nice catch and I'd love to accept the PR and have you listed as a contributor. If you don't have the time, I can add the test to your PR.

**Comment by elmerbulthuis** [comment]
> Left a comment, but I'm not sure if it was seen or not. Can we add a test for this behavior just so we don't lose it in regression? This is a nice catch and I'd love to accept the PR and have you listed as a contributor. If you don't have the time, I can add the test to your PR.

I would love to add a test but i am not that familiar with the way testing is setup. It would be great if you can do that! Or maybe make a start with it.

**Comment by calebdwilliams** [comment]
Testing on this repo just uses web-test-runner and the open-wc tools. I'm happy to add that if you don't want to mess with it.

**Review by calebdwilliams — APPROVED** [review]
LGTM. I'll write up the tests for this.

**Comment by calebdwilliams** [comment]
@elmerbulthuis if you can resolve the conflicts here, I'll be happy to merge and release this.

**Comment by calebdwilliams** [comment]
@elmerbulthuis I added this to `element-internals-polyfill-0.1.51`.

**Pull request closed without merging**
