### PR TITLE
Feature: Add internals-disabled class to disabled element

### PR DESCRIPTION
**Pull request by andrico1234**
closes: https://github.com/calebdwilliams/element-internals-polyfill/issues/41

Happy to discuss this if you need further information. Making this change causes my tests to pass, and it seems inline with browser behaviour. 

I'm not sure if the logic lives in the right places, so am happy to rejig things

## Todo
- [ ] Fix broken test

### CODE REVIEW

**Comment by andrico1234** [comment]
The test that's failing is this one

```
    it('will trigger the formDisabledCallback when disabled', async () => {
      el.disabled = true;
      await elementUpdated(el);
      // Lifecycle methods are stripped off at definition time
      // and added elsewhere so we can't use a spy. Instead
      // we're going to look for a side-effect
      expect(callCount).to.equal(1);
    });
```

When I change the `expect` to 2, the test fails in Chromium but passes in the other two.
When I keep the `expect` to 1, the test passes in Chromium but  fails in the other two.

My first inclination is two break these out into two separate observers, the one with the `formDisabledCallback` logic will not observe changes to `disabled` attribute, with the new observer listening for changes to `disabled`.

**Comment by calebdwilliams** [comment]
Hey @andrico1234, sorry I've not responded yet. I took a bit of time off and this just fell through the cracks. What's still outstanding for this PR on your end? On my end, I'd like to see tests created for the new behavior. But it looks like you were having trouble with a different test?

**Comment by andrico1234** [comment]
Hi Caleb! No worries about the delayed response, I hope you enjoyed your time off ☀️

As far as what's blocking me, I elaborate a little mere [here](https://github.com/calebdwilliams/element-internals-polyfill/issues/41).

IIRC, there's a discrepancy between how the polyfill handles disabled elements from Chrome.

**Comment by calebdwilliams** [comment]
Hey @andrico1234 since there were never any tests added for this PR, I went ahead and made my own version of it and have released it as version `0.1.44`. I realized afterward I probably should have added the test to this PR, sorry about that. I'm closing this PR and the related issue.

**Pull request closed without merging**
