### PR TITLE
fix: call formDisabledCallback in response to fieldset disabled

### LINKED ISSUE #88: Enclosing fieldset's `disabled` attr does not disable polyfilled elements
Please consider https://codepen.io/bennyp/pen/KKemLEG?editors=1010

```html
<form id="form">
  <fieldset id="set" disabled>
    <legend>This fieldset controls <code>x-checkbox</code></legend>
    <label for="xcheck">Check?</label>
    <x-checkbox id="xcheck" name="checkit"></x-checkbox>
  </fieldset>
</form>
```

In this case, using GNOME Web 43.0-66-g2cd7f8ec4+ (WebKitGTK 2.38.2), with the polyfill loaded, I observed that toggling `disabled` on the fieldset had no effect on `x-checkbox`. 

**Expected**: `:disabled` or known-limitations equivalent should be applied to the FACE, mouse clicks should be prevented.

### PR DESCRIPTION
**Pull request by bennypowers**
closes #88 

@calebdwilliams does this test represent expected behavior?

### CODE REVIEW

**Comment by calebdwilliams** [comment]
Yeah, this will capture the expected behavior for polyfilled browsers. I'd want to make sure it works for multiple instances of the form-associated element though.

**Comment by bennypowers** [comment]
does the last commit cover your comment?

**Comment by bennypowers** [comment]
https://github.com/calebdwilliams/element-internals-polyfill/pull/90/commits/854e6843cf39d70bd8b0e246303d3eac78837d50 has some code which might work, but I had some trouble testing. Is it the case that I should test in an isolated virtual machine with older browser versions?

**Comment by calebdwilliams** [comment]
Sorry for the delay in getting to this one. Looks like a test is failing 

```
❌ The ElementInternals polyfill > inside a custom element with a form and containing fieldset > sets aria-disabled when the fieldset is disabled
      AssertionError: expected null to equal 'true'
        at o.<anonymous> (test/ElementInternals.test.js:497:53)

Chromium: |██████████████████████████████| 3/3 test files | 55 passed, 1 failed
Firefox:  |██████████████████████████████| 3/3 test files | 55 passed, 1 failed
Webkit:   |██████████████████████████████| 3/3 test files | 55 passed, 1 failed
```

**Comment by calebdwilliams** [comment]
What problems have you had testing?

**Comment by bennypowers** [comment]
with this, and a peppering of console.log calls throughout the polyfill code, i'm unable to verify that the polyfill is loading at all during that test, let alone whether the fieldsets are registering :/

```js
  describe.only('inside a custom element with a form and containing fieldset', () => {
```

I sent an aspirational commit, maybe it will pass in CI :shrug:  PTAL when you get a chance

**Comment by bennypowers** [comment]
This is what I get when testing.

```
test/polyfilledBrowsers.test.js:

 ❌ The browser was unable to create and start a test page after 30000ms. You can increase this timeout with the browserStartTimeout option.  (failed on Firefox)

 ❌ browserType.launch: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libpcre.so.3                                     ║
║     libicui18n.so.66                                 ║
║     libicuuc.so.66                                   ║
║     libjpeg.so.8                                     ║
║     libwebp.so.6                                     ║
║     libenchant.so.1                                  ║
║     libffi.so.7                                      ║
╚══════════════════════════════════════════════════════╝  (failed on Webkit)
    browserType.launch: 
    ╔══════════════════════════════════════════════════════╗
    ║ Host system is missing dependencies to run browsers. ║
    ║ Missing libraries:                                   ║
    ║     libpcre.so.3                                     ║
    ║     libicui18n.so.66                                 ║
    ║     libicuuc.so.66                                   ║
    ║     libjpeg.so.8                                     ║
    ║     libwebp.so.6                                     ║
    ║     libenchant.so.1                                  ║
    ║     libffi.so.7                                      ║
    ╚══════════════════════════════════════════════════════╝
        at /home/bennyp/Developer/element-internals-polyfill/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:101:74
        at PlaywrightLauncher.getOrStartBrowser (/home/bennyp/Developer/element-internals-polyfill/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:104:15)
        at PlaywrightLauncher.startSession (/home/bennyp/Developer/element-internals-polyfill/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:49)
        at TestScheduler.startSession (/home/bennyp/Developer/element-internals-polyfill/node_modules/@web/test-runner-core/dist/runner/TestScheduler.js:103:62)
        at TestScheduler.runNextScheduled (/home/bennyp/Developer/element-internals-polyfill/node_modules/@web/test-runner-core/dist/runner/TestScheduler.js:83:30)
        at Timeout._onTimeout (/home/bennyp/Developer/element-internals-polyfill/node_modules/@web/test-runner-core/dist/runner/TestScheduler.js:34:26)

Chromium: |██████████████████████████████| 3/3 test files | 8 passed, 1 failed
Firefox:  |██████████████████████████████| 3/3 test files | 0 passed, 0 failed
test/polyfilledBrowsers.test.js:

 ❌ The browser was unable to create and start a test page after 30000ms. You can increase this timeout with the browserStartTimeout option.  (failed on Firefox)

 ❌ browserType.launch: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libpcre.so.3                                     ║
║     libicui18n.so.66                                 ║
║     libicuuc.so.66                                   ║
║     libjpeg.so.8                                     ║
║     libwebp.so.6                                     ║
║     libenchant.so.1                                  ║
║     libffi.so.7                                      ║
╚══════════════════════════════════════════════════════╝  (failed on Webkit)
    browserType.launch: 
    ╔══════════════════════════════════════════════════════╗
    ║ Host system is missing dependencies to run browsers. ║
    ║ Missing libraries:                                   ║
    ║     libpcre.so.3                                     ║
    ║     libicui18n.so.66                                 ║
    ║     libicuuc.so.66                                   ║
    ║     libjpeg.so.8                                     ║
    ║     libwebp.so.6                                     ║
    ║     libenchant.so.1                                  ║
    ║     libffi.so.7                                      ║
    ╚══════════════════════════════════════════════════════╝
        at /home/bennyp/Developer/element-internals-polyfill/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:101:74
        at PlaywrightLauncher.getOrStartBrowser (/home/bennyp/Developer/element-internals-polyfill/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:104:15)
        at PlaywrightLauncher.startSession (/home/bennyp/Developer/element-internals-polyfill/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:49)
        at TestScheduler.startSession (/home/bennyp/Developer/element-internals-polyfill/node_modules/@web/test-runner-core/dist/runner/TestScheduler.js:103:62)
        at TestScheduler.runNextScheduled (/home/bennyp/Developer/element-internals-polyfill/node_modules/@web/test-runner-core/dist/runner/TestScheduler.js:83:30)
        at Timeout._onTimeout (/home/bennyp/Developer/element-internals-polyfill/node_modules/@web/test-runner-core/dist/runner/TestScheduler.js:34:26)

Chromium: |██████████████████████████████| 3/3 test files | 8 passed, 1 failed
Firefox:  |██████████████████████████████| 3/3 test files | 0 passed, 0 failed
test/polyfilledBrowsers.test.js:

 ❌ The browser was unable to create and start a test page after 30000ms. You can increase this timeout with the browserStartTimeout option.  (failed on Firefox)

 ❌ browserType.launch: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libpcre.so.3                                     ║
║     libicui18n.so.66                                 ║
║     libicuuc.so.66                                   ║
║     libjpeg.so.8                                     ║
║     libwebp.so.6                                     ║
║     libenchant.so.1                                  ║
║     libffi.so.7                                      ║
╚══════════════════════════════════════════════════════╝  (failed on Webkit)
    browserType.launch: 
    ╔══════════════════════════════════════════════════════╗
    ║ Host system is missing dependencies to run browsers. ║
    ║ Missing libraries:                                   ║
    ║     libpcre.so.3                                     ║
    ║     libicui18n.so.66                                 ║
    ║     libicuuc.so.66                                   ║
    ║     libjpeg.so.8                                     ║
    ║     libwebp.so.6                                     ║
    ║     libenchant.so.1                                  ║
    ║     libffi.so.7                                      ║
    ╚══════════════════════════════════════════════════════╝
        at /home/bennyp/Developer/element-internals-polyfill/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:101:74
        at PlaywrightLauncher.getOrStartBrowser (/home/bennyp/Developer/element-internals-polyfill/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:104:15)
        at PlaywrightLauncher.startSession (/home/bennyp/Developer/element-internals-polyfill/node_modules/@web/test-runner-playwright/dist/PlaywrightLauncher.js:42:49)
        at TestScheduler.startSession (/home/bennyp/Developer/element-internals-polyfill/node_modules/@web/test-runner-core/dist/runner/TestScheduler.js:103:62)
        at TestScheduler.runNextScheduled (/home/bennyp/Developer/element-internals-polyfill/node_modules/@web/test-runner-core/dist/runner/TestScheduler.js:83:30)
        at Timeout._onTimeout (/home/bennyp/Developer/element-internals-polyfill/node_modules/@web/test-runner-core/dist/runner/TestScheduler.js:34:26)

Chromium: |██████████████████████████████| 3/3 test files | 8 passed, 1 failed
Firefox:  |██████████████████████████████| 3/3 test files | 0 passed, 0 failed
Webkit:   |██████████████████████████████| 3/3 test files | 0 passed, 0 failed
```

**Comment by calebdwilliams** [comment]
Can you run `npx playwright install --with-deps` locally and/or force push? I finally added a test action to PRs and we can get this out the door once it's ready.

**Comment by bennypowers** [comment]
This is great work, thanks for investigating, @calebdwilliams 

So if I understood correctly, that means the polyfill cannot provide `matches(':disabled')`, right?

**Comment by calebdwilliams** [comment]
Unfortunately I don’t think it can but there’s a lot I don’t know. I think @jonathantneal might have a way to do this with CSSOM shenanigans. Maybe he can ping us in the right direction.

**Comment by calebdwilliams** [comment]
@bennypowers isbthis something you’re still interested in tackling?

**Comment by bennypowers** [comment]
yes, i'll take a go at it in light of above comments tomorrow

**Comment by jonathantneal** [comment]
To support `:disabled`, this library would need to patch the query methods (`querySelector`, `querySelectorAll`, and `matches`) akin to how it patches `attachShadow`. That patch could also be used to support `:--state` as well.

What would it replace `:disabled` with? I suppose elements could maintain their LightDOM selector (that is, custom element, itself.)

Here’s how they could generate that reference.
```js
/** Return a unique selector for a specific element. */
let getUniqueSelector = (/** @type {Element} */ element) => {
	/** Unique selector for this element */
	let selector = ''

	/** @type {Element} */
	let parent

	/** @type {number} */
	let nth

	while (parent = element.parentElement) {
		for (nth = 1; element = element.previousElementSibling; ++nth);

		selector = ' > :nth-child(' + nth + ')' + selector

		element = parent
	}

	return ':root' + selector
}
```

And then elements could push that selector up to some map that replaces those states on selectors, like ``selector.replace(":disabled", `:where(${selectorsFor.disabled})`)``. As a gist, does this make sense?

Happy to help try to contribute something like this, if it would be desired / helpful. If it isn’t, no worries.

**Comment by calebdwilliams** [comment]
Fixed in a different PR

**Pull request closed without merging**
