### PR TITLE
[FIX] ~patch :bug: Fix selector [for=InvalidChar[]] to [for="encapsul…

### PR DESCRIPTION
**Pull request by odeniel**
…ated"]

[Link a la tarea element](https://apps.edicomgroup.com/JDev/#idstask|element) /label ~"status::needs triage" ~type::fix ~patch
/assign me

### CODE REVIEW

**Comment by calebdwilliams** [comment]
I’d love the contribution but could you please revert the styling differences?

**Comment by odeniel** [comment]
Sorry about problem styling, I'll send fixed

**Comment by odeniel** [comment]
OK, sorry about that, now seems better, please let me know.

**Review by calebdwilliams — APPROVED** [review]
Thanks!

**Comment by odeniel** [comment]
Done!

**Pull request merged**
