### PR TITLE
Fix `formDisabledCallback` order to match native implementations

### PR DESCRIPTION
**Pull request by jpzwarte**
So this moves the `setDisabled` call from `initRef` to `initNode`. By doing that, `formDisabledCallback` is called *after* `connectedCallback` instead of before the constructor.

### CODE REVIEW

**Comment by calebdwilliams** [comment]
Could we get a test for this one?

**Comment by jpzwarte** [comment]
@calebdwilliams I've added a test that succeeds on Chrome & Firefox, but fails on Webkit. The reason for that is that the `formDisabledCallback` is called *after* `connectedCallback` on Webkit. On Chrome & Firefox, it is called before.

Any ideas on how to fix that?

**Comment by jpzwarte** [comment]
@calebdwilliams this seems like the solution, except *it doesn't work*. I don't understand why; do you?

```ts
export const initRef = (ref: ICustomElement, internals: IElementInternals): void => {
  hiddenInputMap.set(internals, []);

  const connectedCallback = ref.connectedCallback;
  ref.connectedCallback = function(...args) {
    if (this.hasAttribute('disabled')) {
      setDisabled(this, true);
    }

    connectedCallback.call(this, args);

    console.log('HOHOHOO', ref);    
  };

  observer.observe(ref, observerConfig);
};
```

The custom `connectedCallback` method never get's called.

**Comment by jpzwarte** [comment]
@calebdwilliams I managed to get it working by changing my approach: I now override the `connectedCallback` method when `customElements.define(...)` is called. This approach works! So the PR is now ready for review please :)

**Comment by calebdwilliams** [comment]
This looks good to me so far. Can you do a force push just to verify it works? I added a test action and want to make sure it runs there before approving/merging?

**Comment by calebdwilliams** [comment]
What impact would this have on elements created using `document.createElement` or on elements that get disconnected then reconnected?

**Comment by jpzwarte** [comment]
@calebdwilliams Good catch! I've made sure `formDisabledCallback` only get's called during the first `connectedCallback` (plus a test). 
I don't see how this change would affect element created with `document.createElement`? The entire `connectedCallback` override is behind a `if (constructor.formAssociated) {` guard.

**Review by calebdwilliams — APPROVED** [review]
lgtm

**Comment by calebdwilliams** [comment]
This has been published as `element-internals-polyfill@1.1.19`. Thanks @jpzwarte!

**Pull request merged**
