### PR TITLE
form.elements for associated custom elements

### LINKED ISSUE #43: form.elements still not polyfilled
As a workaround I added `form._elements = initSet` in order to get the elements from the internal set. Better than nothing.

### PR DESCRIPTION
**Pull request by ubermanu**
Form elements override proposed by @jrj2211 in #43 

- [x] add tests

Closes #43

### CODE REVIEW

**Comment by calebdwilliams** [comment]
Ping me when this is ready for review.

**Comment by ubermanu** [comment]
@calebdwilliams all set

I wasn't much inspired for the testing part, but the collection should be properly sorted

**Comment by calebdwilliams** [comment]
Could you resolve the conflicts on this PR? Hopefully I can get to it tomorrow once that's done.

**Comment by ubermanu** [comment]
hey Caleb, I've resolved them a few days ago already (or if you were thinking of something else?)

**Comment by calebdwilliams** [comment]
GitHub is saying this can’t be rebased, but it can be squashed. I’ll just do that.

**Comment by calebdwilliams** [comment]
Released as `element-internals-polyfill@1.2.0`

**Pull request merged**
